// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendingControl.API.Data;

namespace SpendingControl.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201124050730_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SpendingControl.API.Models.FixedSpend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WhereId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WhereSpentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WhereSpentId");

                    b.ToTable("FixedSpends");
                });

            modelBuilder.Entity("SpendingControl.API.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("SpendingControl.API.Models.InstalledSpend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtyInstallments")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WhereId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WhereSpentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WhereSpentId");

                    b.ToTable("InstalledSpends");
                });

            modelBuilder.Entity("SpendingControl.API.Models.WhereSpent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WhereSpents");
                });

            modelBuilder.Entity("SpendingControl.API.Models.FixedSpend", b =>
                {
                    b.HasOne("SpendingControl.API.Models.WhereSpent", "WhereSpent")
                        .WithMany()
                        .HasForeignKey("WhereSpentId");

                    b.Navigation("WhereSpent");
                });

            modelBuilder.Entity("SpendingControl.API.Models.InstalledSpend", b =>
                {
                    b.HasOne("SpendingControl.API.Models.WhereSpent", "WhereSpent")
                        .WithMany()
                        .HasForeignKey("WhereSpentId");

                    b.Navigation("WhereSpent");
                });
#pragma warning restore 612, 618
        }
    }
}
